---
  JOB_ID: "safespace-nlp"
   
  PARAMS:
    base_dir: "working-version_v3/"
    source_data_dir: "Annotations_MV/" 
    epochs: 40
    batch_size: 64
    lr: 0.0001
    shuffle_seed: 42
    sv_model_path: "sentence-transformers/nli-roberta-large"
    wv_model_path: "lexicon/wiki-news-300d-1M.vec"
  EXPORT:
    log_dir: "logs"
    dataset_dir: "data"
    checkpoint_dir: "checkpoints"
